-- MySQL Script generated by MySQL Workbench
-- Tue Dec 31 16:28:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mg_doc(binh)
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mg_doc(binh)
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mg_doc(binh)` DEFAULT CHARACTER SET utf8mb3 ;
USE `db_mg_doc(binh)` ;

-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`formstore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`formstore` (
  `IDFormStore` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb3' NOT NULL,
  `Description` VARCHAR(150) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`IDFormStore`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  UNIQUE INDEX `IDFormStore_UNIQUE` (`IDFormStore` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`form` (
  `IDForm` INT NOT NULL AUTO_INCREMENT,
  `IDFormStore` INT NOT NULL,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb3' NOT NULL,
  `Type` VARCHAR(25) NULL DEFAULT NULL,
  `Language` VARCHAR(45) NULL DEFAULT NULL,
  `FileSize` INT NULL DEFAULT NULL,
  `FileData` LONGBLOB NOT NULL,
  PRIMARY KEY (`IDForm`, `IDFormStore`),
  UNIQUE INDEX `IDForm_UNIQUE` (`IDForm` ASC),
  INDEX `fk_Form_FormStore1_idx` (`IDFormStore` ASC),
  CONSTRAINT `fk_Form_FormStore1`
    FOREIGN KEY (`IDFormStore`)
    REFERENCES `db_mg_doc(binh)`.`formstore` (`IDFormStore`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`office` (
  `IDOffice` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Manager` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `NumberOfMember` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDOffice`),
  UNIQUE INDEX `IDOffice_UNIQUE` (`IDOffice` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`office_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`office_work` (
  `IDOfficeWork` INT NOT NULL AUTO_INCREMENT,
  `Position` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `IDOffice` INT NOT NULL,
  PRIMARY KEY (`IDOfficeWork`, `IDOffice`),
  INDEX `fk_office_work_office1_idx` (`IDOffice` ASC),
  CONSTRAINT `fk_office_work_office1`
    FOREIGN KEY (`IDOffice`)
    REFERENCES `db_mg_doc(binh)`.`office` (`IDOffice`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`sex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`sex` (
  `IDSex` INT NOT NULL,
  `Sex` NVARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDSex`),
  UNIQUE INDEX `IDSex_UNIQUE` (`IDSex` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`department` (
  `IDDepartment` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Manager` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `NumberOfMember` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDDepartment`),
  UNIQUE INDEX `IDDepartment_UNIQUE` (`IDDepartment` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`department_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`department_work` (
  `IDDepartmentWork` INT NOT NULL AUTO_INCREMENT,
  `IDDepartment` INT NOT NULL,
  `Position` VARCHAR(70) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`IDDepartmentWork`, `IDDepartment`),
  INDEX `fk_work_Department1_idx` (`IDDepartment` ASC),
  CONSTRAINT `fk_work_Department1`
    FOREIGN KEY (`IDDepartment`)
    REFERENCES `db_mg_doc(binh)`.`department` (`IDDepartment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`admin` (
  `IDAdmin` INT NOT NULL AUTO_INCREMENT,
  `Name` NVARCHAR(225) CHARACTER SET 'utf8mb3' NOT NULL,
  `NickName` NVARCHAR(225) NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `Nation` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `Picture` VARCHAR(255) NULL DEFAULT NULL,
  `Description` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `IDSex` INT NOT NULL,
  `IDDepartmentWork` INT NULL DEFAULT NULL,
  `IDOfficeWork` INT NULL DEFAULT NULL,
  `IDForm` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDAdmin`),
  UNIQUE INDEX `IDAdmin_UNIQUE` (`IDAdmin` ASC),
  INDEX `fk_admin_sex1_idx` (`IDSex` ASC),
  INDEX `fk_admin_work1_idx` (`IDDepartmentWork` ASC),
  INDEX `fk_admin_office_work1_idx` (`IDOfficeWork` ASC),
  INDEX `fk_admin_Form1_idx` (`IDForm` ASC),
  CONSTRAINT `fk_admin_Form1`
    FOREIGN KEY (`IDForm`)
    REFERENCES `db_mg_doc(binh)`.`form` (`IDForm`),
  CONSTRAINT `fk_admin_office_work1`
    FOREIGN KEY (`IDOfficeWork`)
    REFERENCES `db_mg_doc(binh)`.`office_work` (`IDOfficeWork`),
  CONSTRAINT `fk_admin_sex1`
    FOREIGN KEY (`IDSex`)
    REFERENCES `db_mg_doc(binh)`.`sex` (`IDSex`),
  CONSTRAINT `fk_admin_work1`
    FOREIGN KEY (`IDDepartmentWork`)
    REFERENCES `db_mg_doc(binh)`.`department_work` (`IDDepartmentWork`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`admin_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`admin_roles` (
  `IDAdminRole` INT NOT NULL AUTO_INCREMENT,
  `KeyRoles` ENUM('Super', 'Manager', 'Dev') NOT NULL DEFAULT 'Manager',
  PRIMARY KEY (`IDAdminRole`),
  UNIQUE INDEX `KeyRoles_UNIQUE` (`KeyRoles` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`admin_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`admin_account` (
  `IDAdminAcc` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `AccuracyCode` INT NULL DEFAULT NULL,
  `Enabled` TINYINT NOT NULL DEFAULT 0,
  `IDAdminRole` INT NOT NULL DEFAULT 2,
  `IDAdmin` INT NOT NULL,
  PRIMARY KEY (`IDAdminAcc`, `IDAdmin`),
  UNIQUE INDEX `IDAdminAcc_UNIQUE` (`IDAdminAcc` ASC),
  UNIQUE INDEX `IDAdmin_UNIQUE` (`IDAdmin` ASC),
  INDEX `fk_admin_account_admin_roles1_idx` (`IDAdminRole` ASC),
  INDEX `fk_admin_account_admin1_idx` (`IDAdmin` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  CONSTRAINT `fk_admin_account_admin1`
    FOREIGN KEY (`IDAdmin`)
    REFERENCES `db_mg_doc(binh)`.`admin` (`IDAdmin`),
  CONSTRAINT `fk_admin_account_admin_roles1`
    FOREIGN KEY (`IDAdminRole`)
    REFERENCES `db_mg_doc(binh)`.`admin_roles` (`IDAdminRole`))
ENGINE = InnoDB
AUTO_INCREMENT = 343041976
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`admin_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`admin_address` (
  `IDAdmin` INT NOT NULL,
  `StreetName` NVARCHAR(255) NULL DEFAULT NULL,
  `City` NVARCHAR(255) NULL DEFAULT NULL,
  `Province` NVARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDAdmin`),
  CONSTRAINT `fk_admin_address_admin1`
    FOREIGN KEY (`IDAdmin`)
    REFERENCES `db_mg_doc(binh)`.`admin` (`IDAdmin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`admin_education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`admin_education` (
  `IDAdmin` INT NOT NULL,
  `School` NVARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDAdmin`),
  CONSTRAINT `fk_admin_education_admin1`
    FOREIGN KEY (`IDAdmin`)
    REFERENCES `db_mg_doc(binh)`.`admin` (`IDAdmin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`admin_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`admin_skill` (
  `IDAdmin` INT NOT NULL,
  `Description` NVARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDAdmin`),
  CONSTRAINT `fk_admin_skill_admin1`
    FOREIGN KEY (`IDAdmin`)
    REFERENCES `db_mg_doc(binh)`.`admin` (`IDAdmin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`doccument_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`doccument_store` (
  `IDDoccumentStore` INT NOT NULL AUTO_INCREMENT,
  `NameStore` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `Description` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`IDDoccumentStore`),
  UNIQUE INDEX `IDDoccumentStore_UNIQUE` (`IDDoccumentStore` ASC),
  UNIQUE INDEX `NameStore_UNIQUE` (`NameStore` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`user` (
  `IDUser` INT NOT NULL AUTO_INCREMENT,
  `Name` NVARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `NickName` NVARCHAR(255) NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `Nation` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `Picture` VARCHAR(255) NULL DEFAULT NULL,
  `Description` VARCHAR(150) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `IDSex` INT NOT NULL,
  `IDOfficeWork` INT NULL DEFAULT NULL,
  `IDDepartmentWork` INT NULL DEFAULT NULL,
  `IDForm` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDUser`),
  UNIQUE INDEX `IDUser_UNIQUE` (`IDUser` ASC),
  INDEX `fk_user_sex1_idx` (`IDSex` ASC),
  INDEX `fk_user_office_work1_idx` (`IDOfficeWork` ASC),
  INDEX `fk_user_department_work1_idx` (`IDDepartmentWork` ASC),
  INDEX `fk_user_Form1_idx` (`IDForm` ASC),
  CONSTRAINT `fk_user_department_work1`
    FOREIGN KEY (`IDDepartmentWork`)
    REFERENCES `db_mg_doc(binh)`.`department_work` (`IDDepartmentWork`),
  CONSTRAINT `fk_user_Form1`
    FOREIGN KEY (`IDForm`)
    REFERENCES `db_mg_doc(binh)`.`form` (`IDForm`),
  CONSTRAINT `fk_user_office_work1`
    FOREIGN KEY (`IDOfficeWork`)
    REFERENCES `db_mg_doc(binh)`.`office_work` (`IDOfficeWork`),
  CONSTRAINT `fk_user_sex1`
    FOREIGN KEY (`IDSex`)
    REFERENCES `db_mg_doc(binh)`.`sex` (`IDSex`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`doccument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`doccument` (
  `IDDoccument` INT NOT NULL AUTO_INCREMENT,
  `IDDoccumentStore` INT NOT NULL,
  `Title` NVARCHAR(255) NOT NULL,
  `Author` NVARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `Status` ENUM('Pending', 'Approved', 'Rejected') NOT NULL,
  `FileSize` INT NULL DEFAULT NULL,
  `FileData` LONGBLOB NOT NULL,
  `IDDepartment` INT NULL DEFAULT NULL,
  `IDAdmin` INT NOT NULL,
  `IDUser` INT NULL,
  PRIMARY KEY (`IDDoccument`, `IDDoccumentStore`),
  INDEX `fk_doccument_doccument_store1_idx` (`IDDoccumentStore` ASC),
  INDEX `fk_doccument_Department1_idx` (`IDDepartment` ASC),
  INDEX `fk_doccument_admin1_idx` (`IDAdmin` ASC),
  INDEX `fk_doccument_user1_idx` (`IDUser` ASC),
  CONSTRAINT `fk_doccument_Department`
    FOREIGN KEY (`IDDepartment`)
    REFERENCES `db_mg_doc(binh)`.`department` (`IDDepartment`),
  CONSTRAINT `fk_doccument_doccument_store`
    FOREIGN KEY (`IDDoccumentStore`)
    REFERENCES `db_mg_doc(binh)`.`doccument_store` (`IDDoccumentStore`),
  CONSTRAINT `fk_doccument_admin`
    FOREIGN KEY (`IDAdmin`)
    REFERENCES `db_mg_doc(binh)`.`admin` (`IDAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doccument_user`
    FOREIGN KEY (`IDUser`)
    REFERENCES `db_mg_doc(binh)`.`user` (`IDUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`genres` (
  `IDGenres` INT NOT NULL AUTO_INCREMENT,
  `GenresName` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `Description` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`IDGenres`),
  UNIQUE INDEX `GenresName_UNIQUE` (`GenresName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`doccument_has_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`doccument_has_genres` (
  `IDDoccument` INT NOT NULL,
  `IDDoccumentStore` INT NOT NULL,
  `IDGenres` INT NOT NULL,
  `Descripstion` VARCHAR(150) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`IDDoccument`, `IDDoccumentStore`, `IDGenres`),
  INDEX `fk_doccument_has_genres_genres1_idx` (`IDGenres` ASC),
  INDEX `fk_doccument_has_genres_doccument1_idx` (`IDDoccument` ASC, `IDDoccumentStore` ASC),
  CONSTRAINT `fk_doccument_has_genres_doccument1`
    FOREIGN KEY (`IDDoccument` , `IDDoccumentStore`)
    REFERENCES `db_mg_doc(binh)`.`doccument` (`IDDoccument` , `IDDoccumentStore`),
  CONSTRAINT `fk_doccument_has_genres_genres1`
    FOREIGN KEY (`IDGenres`)
    REFERENCES `db_mg_doc(binh)`.`genres` (`IDGenres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`testsyn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`testsyn` (
  `idTestSyn` INT NOT NULL,
  PRIMARY KEY (`idTestSyn`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`user_roles` (
  `IDUserRole` INT NOT NULL AUTO_INCREMENT,
  `KeyRoles` ENUM('Author', 'Manager', 'Student') NOT NULL DEFAULT 'Student',
  PRIMARY KEY (`IDUserRole`),
  UNIQUE INDEX `KeyRoles_UNIQUE` (`KeyRoles` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`user_account` (
  `IDUserAcc` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Enabled` TINYINT NOT NULL,
  `IDUserRole` INT NOT NULL,
  `IDUser` INT NOT NULL,
  PRIMARY KEY (`IDUserAcc`, `IDUser`),
  UNIQUE INDEX `IDUserAcc_UNIQUE` (`IDUserAcc` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `IDUser_UNIQUE` (`IDUser` ASC),
  INDEX `fk_user_account_user_roles1_idx` (`IDUserRole` ASC),
  INDEX `fk_user_account_user1_idx` (`IDUser` ASC),
  CONSTRAINT `fk_user_account_user1`
    FOREIGN KEY (`IDUser`)
    REFERENCES `db_mg_doc(binh)`.`user` (`IDUser`),
  CONSTRAINT `fk_user_account_user_roles1`
    FOREIGN KEY (`IDUserRole`)
    REFERENCES `db_mg_doc(binh)`.`user_roles` (`IDUserRole`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`user_address` (
  `IDUser` INT NOT NULL,
  `StreetName` VARCHAR(255) NULL DEFAULT NULL,
  `City` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `Province` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`IDUser`),
  CONSTRAINT `fk_user_address_user1`
    FOREIGN KEY (`IDUser`)
    REFERENCES `db_mg_doc(binh)`.`user` (`IDUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`user_education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`user_education` (
  `IDUser` INT NOT NULL,
  `School` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDUser`),
  CONSTRAINT `fk_user_education_user1`
    FOREIGN KEY (`IDUser`)
    REFERENCES `db_mg_doc(binh)`.`user` (`IDUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`user_request_capability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`user_request_capability` (
  `IDUserRequestCapability` INT NOT NULL AUTO_INCREMENT,
  `KeyCapability` ENUM('Author', 'Manager', 'Student') NULL DEFAULT 'Student',
  `Description` VARCHAR(150) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `IDAdmin` INT NOT NULL,
  `IDUser` INT NOT NULL,
  PRIMARY KEY (`IDUserRequestCapability`, `IDAdmin`, `IDUser`),
  INDEX `fk_user_request_capability_admin1_idx` (`IDAdmin` ASC),
  INDEX `fk_user_request_capability_user1_idx` (`IDUser` ASC),
  UNIQUE INDEX `IDUser_UNIQUE` (`IDUser` ASC),
  UNIQUE INDEX `IDUserRequestCapability_UNIQUE` (`IDUserRequestCapability` ASC),
  CONSTRAINT `fk_user_request_capability_admin1`
    FOREIGN KEY (`IDAdmin`)
    REFERENCES `db_mg_doc(binh)`.`admin` (`IDAdmin`),
  CONSTRAINT `fk_user_request_capability_user1`
    FOREIGN KEY (`IDUser`)
    REFERENCES `db_mg_doc(binh)`.`user` (`IDUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_mg_doc(binh)`.`user_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mg_doc(binh)`.`user_skill` (
  `IDUser` INT NOT NULL,
  `Description` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`IDUser`),
  CONSTRAINT `fk_user_skill_user1`
    FOREIGN KEY (`IDUser`)
    REFERENCES `db_mg_doc(binh)`.`user` (`IDUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
