# Root logger option
log4j.rootLogger=INFO, console

# Console output
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.Target=System.out
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Set logging level for Spring MVC
log4j.logger.org.springframework.web=DEBUG
log4j.logger.org.springframework=DEBUG


spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.mvc.locale=vi_VN
spring.mvc.locale-resolver=fixed

upload.dir=E:/data/binh_document
